# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20170304_1414'),
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='Course_Org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u8bfe\u7a0b\u673a\u6784'),
        ),
    ]
