# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_demo_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m', verbose_name='\u89c6\u9891\u5c01\u9762'),
        ),
    ]
