# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_auto_20170304_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570'),
        ),
    ]
