# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0005_demo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
