# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0008_demo_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60'),
        ),
        migrations.AddField(
            model_name='demo',
            name='you_need_know',
            field=models.CharField(default='', max_length=300, verbose_name='\u4f60\u9700\u8981\u77e5\u9053'),
        ),
    ]
