# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_courseorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='categroy',
            field=models.CharField(choices=[('kcjg', '\u8bfe\u7a0b\u673a\u6784'), ('gr', '\u4e2a\u4eba'), ('gx', '\u9ad8\u6821')], default='gr', max_length=100),
        ),
    ]
