# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_categroy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='categroy',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gr', '\u4e2a\u4eba'), ('gx', '\u9ad8\u6821')], default='gr', max_length=100, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
    ]
