# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20170301_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=200, verbose_name='\u5de5\u4f5c\u804c\u4f4d'),
        ),
    ]
